import { mkdir, writeFile } from 'node:fs/promises';
import type { PersonaCatalogRecord, SeedCatalogFile, SeedRuntimeConfig } from './types';

function toGuideMarkdown(config: SeedRuntimeConfig, records: PersonaCatalogRecord[]): string {
    const lines: string[] = [
        '# Test Agent Accounts (Local)',
        '',
        'Generated by `scripts/seed-test-accounts.ts`.',
        '',
        `Seed source: \`${config.seedSource}\``,
        '',
        '> This file is local-only and contains credentials for automated testing.',
        '',
        '| Persona | Email | Password | Org Slug | Role | State |',
        '| --- | --- | --- | --- | --- | --- |',
    ];

    for (const record of records) {
        lines.push(
            `| ${record.key} | ${record.email} | ${record.password ?? '-'} | ${record.organizationSlug ?? '-'} | ${record.roleKey} | ${record.state} |`,
        );
    }

    lines.push('');
    lines.push('## Expected Behaviour');
    lines.push('');
    for (const record of records) {
        lines.push(`- \`${record.key}\`: ${record.expectedResult}`);
    }

    lines.push('');
    lines.push('## Usage');
    lines.push('');
    lines.push('- Login URL: `/login?org=<org-slug>`');
    lines.push('- Post-login URL: `/api/auth/post-login?org=<org-slug>&next=/dashboard`');
    lines.push('');
    return lines.join('\n');
}

export async function writeLocalCatalog(
    config: SeedRuntimeConfig,
    records: PersonaCatalogRecord[],
): Promise<void> {
    await mkdir(config.outputDir, { recursive: true });

    const payload: SeedCatalogFile = {
        generatedAt: new Date().toISOString(),
        seedSource: config.seedSource,
        personas: records,
    };

    await writeFile(config.localCatalogPath, JSON.stringify(payload, null, 2), 'utf8');
    await writeFile(config.localGuidePath, toGuideMarkdown(config, records), 'utf8');
}

