import type { OrganizationSeedConfig, PersonaSeedConfig } from './types';

const ORG_DEFAULTS = {
    tenantId: 'orgcentral-platform',
    regionCode: 'UK-LON',
    dataResidency: 'UK_ONLY',
    dataClassification: 'OFFICIAL',
} as const;

export const ORGANIZATION_SEEDS: readonly OrganizationSeedConfig[] = [
    {
        key: 'platform',
        slug: 'orgcentral-platform',
        name: 'OrgCentral Platform',
        ...ORG_DEFAULTS,
        mfaRequired: false,
    },
    {
        key: 'alpha',
        slug: 'orgcentral-alpha',
        name: 'OrgCentral Alpha',
        ...ORG_DEFAULTS,
        mfaRequired: false,
    },
    {
        key: 'beta',
        slug: 'orgcentral-beta',
        name: 'OrgCentral Beta',
        ...ORG_DEFAULTS,
        mfaRequired: true,
    },
] as const;

export const PERSONA_SEEDS: readonly PersonaSeedConfig[] = [
    {
        key: 'platform_admin_ready',
        state: 'ready',
        displayName: 'Platform Admin Ready',
        emailLocalPart: 'platform.admin.ready',
        roleKey: 'globalAdmin',
        organizationKey: 'platform',
        hasPassword: true,
        profileMode: 'none',
        membershipMode: 'ACTIVE',
        twoFactorEnabled: false,
        notes: 'Global admin with credential login and full platform access.',
    },
    {
        key: 'org_beta_admin_mfa_required',
        state: 'mfa_setup_required',
        displayName: 'Org Beta Admin MFA Required',
        emailLocalPart: 'org.beta.admin.mfa.required',
        roleKey: 'orgAdmin',
        organizationKey: 'beta',
        hasPassword: true,
        profileMode: 'ready',
        membershipMode: 'ACTIVE',
        twoFactorEnabled: false,
        notes: 'Org admin expected to be redirected to MFA setup by org policy.',
    },
    {
        key: 'org_alpha_admin_ready',
        state: 'ready',
        displayName: 'Org Alpha Admin Ready',
        emailLocalPart: 'org.alpha.admin.ready',
        roleKey: 'orgAdmin',
        organizationKey: 'alpha',
        hasPassword: true,
        profileMode: 'ready',
        membershipMode: 'ACTIVE',
        twoFactorEnabled: false,
        notes: 'Tenant org admin with complete profile.',
    },
    {
        key: 'org_alpha_hr_manager_ready',
        state: 'ready',
        displayName: 'Org Alpha HR Manager Ready',
        emailLocalPart: 'org.alpha.hr.manager.ready',
        roleKey: 'hrAdmin',
        organizationKey: 'alpha',
        hasPassword: true,
        profileMode: 'ready',
        membershipMode: 'ACTIVE',
        twoFactorEnabled: false,
        notes: 'HR manager persona for people/compliance workflows.',
    },
    {
        key: 'org_alpha_member_profile_pending',
        state: 'profile_setup_required',
        displayName: 'Org Alpha Member Profile Pending',
        emailLocalPart: 'org.alpha.member.profile.pending',
        roleKey: 'member',
        organizationKey: 'alpha',
        hasPassword: true,
        profileMode: 'pending',
        membershipMode: 'ACTIVE',
        twoFactorEnabled: false,
        notes: 'Active member without mandatory first/last profile fields.',
    },
    {
        key: 'org_alpha_member_password_pending',
        state: 'password_setup_required',
        displayName: 'Org Alpha Member Password Pending',
        emailLocalPart: 'org.alpha.member.password.pending',
        roleKey: 'member',
        organizationKey: 'alpha',
        hasPassword: false,
        profileMode: 'ready',
        membershipMode: 'ACTIVE',
        twoFactorEnabled: false,
        notes: 'Active member without credential account; must set password.',
    },
    {
        key: 'org_beta_member_suspended',
        state: 'suspended',
        displayName: 'Org Beta Member Suspended',
        emailLocalPart: 'org.beta.member.suspended',
        roleKey: 'member',
        organizationKey: 'beta',
        hasPassword: true,
        profileMode: 'ready',
        membershipMode: 'SUSPENDED',
        twoFactorEnabled: false,
        notes: 'Suspended member to validate membership guard enforcement.',
    },
    {
        key: 'user_no_membership',
        state: 'no_membership',
        displayName: 'No Membership User',
        emailLocalPart: 'user.no.membership',
        roleKey: 'member',
        hasPassword: true,
        profileMode: 'none',
        membershipMode: 'NONE',
        twoFactorEnabled: false,
        notes: 'Authenticated user with no org membership; should route to not-invited.',
    },
] as const;
