import type {
    EnterpriseOnboardingInput,
    ModuleAccessUpdateInput,
} from '@/server/repositories/contracts/org/enterprise/enterprise-admin-repository-contract';
import type { ManagedOrganizationSummary } from '@/server/types/enterprise-types';
import type { JsonValue } from '@/server/repositories/prisma/helpers/prisma-utils';
import { normalizeMetadata } from '@/server/repositories/mappers/metadata';

export type ManagedOrganizationRecord = {
    orgId: string;
    orgName: string;
    ownerEmail: string;
    planId: string;
    moduleAccess: Record<string, boolean>;
    metadata?: JsonValue | null;
    createdAt: Date | string;
    updatedAt: Date | string;
};

export function mapManagedOrganizationRecordToDomain(record: ManagedOrganizationRecord): ManagedOrganizationSummary {
    return {
        orgId: record.orgId,
        orgName: record.orgName,
        ownerEmail: record.ownerEmail,
        planId: record.planId,
        moduleAccess: record.moduleAccess,
        metadata: normalizeMetadata(record.metadata),
        createdAt: record.createdAt instanceof Date ? record.createdAt : new Date(record.createdAt),
        updatedAt: record.updatedAt instanceof Date ? record.updatedAt : new Date(record.updatedAt),
    };
}

export function mapEnterpriseOnboardingInputToRecord(
    input: EnterpriseOnboardingInput,
): Omit<ManagedOrganizationRecord, 'createdAt' | 'updatedAt'> {
    return {
        orgId: '', // to be generated by persistence layer
        orgName: input.orgName,
        ownerEmail: input.ownerEmail,
        planId: input.planId,
        moduleAccess: input.moduleAccess,
    };
}

export function mapModuleAccessUpdateToRecord(
    input: ModuleAccessUpdateInput,
): Pick<ManagedOrganizationRecord, 'moduleAccess'> {
    return { moduleAccess: input.moduleAccess };
}
