export const HR_TIME_TRACKING_LIMITS = {
    TASKS_MAX_COUNT: 200,
    TASKS_MAX_LENGTH: 200,
    PROJECT_MAX_LENGTH: 200,
    NOTES_MAX_LENGTH: 2000,
    MAX_HOURS_PER_DAY: 24,
    BREAK_DURATION_MAX_HOURS: 24,
    PROJECT_CODE_MAX_LENGTH: 120,
    OVERTIME_REASON_MAX_LENGTH: 500,
} as const;

export type HrTimeTrackingLimits = typeof HR_TIME_TRACKING_LIMITS;