import { RoleScope } from '@/server/types/prisma';
import type { OrgPermissionMap } from './access-control';
import { ROLE_PERMISSION_STATEMENTS } from './role-permission-statements';

export const orgAdminTemplate = {
  name: 'orgAdmin',
  description: 'Organization administrator with HR admin access.',
  scope: RoleScope.ORG,
  permissions: {
    'org.settings': ['read', 'update'],
    member: ['read', 'invite', 'update'],
    invitation: ROLE_PERMISSION_STATEMENTS.invitation,
    cache: ROLE_PERMISSION_STATEMENTS.cache,
    'hr.absence': ROLE_PERMISSION_STATEMENTS['hr.absence'],
    'hr.absence.settings': ROLE_PERMISSION_STATEMENTS['hr.absence.settings'],
    'hr.absence.attachment': ROLE_PERMISSION_STATEMENTS['hr.absence.attachment'],
    'hr.compliance.item': ROLE_PERMISSION_STATEMENTS['hr.compliance.item'],
    'hr.compliance.template': ROLE_PERMISSION_STATEMENTS['hr.compliance.template'],
    'hr.compliance.review': ROLE_PERMISSION_STATEMENTS['hr.compliance.review'],
    'hr.leave.request': ROLE_PERMISSION_STATEMENTS['hr.leave.request'],
    'hr.leave.balance': ROLE_PERMISSION_STATEMENTS['hr.leave.balance'],
    'hr.leave.policy': ROLE_PERMISSION_STATEMENTS['hr.leave.policy'],
    'hr.leave.type': ROLE_PERMISSION_STATEMENTS['hr.leave.type'],
    'hr.notification': ROLE_PERMISSION_STATEMENTS['hr.notification'],
    'hr.reminder': ROLE_PERMISSION_STATEMENTS['hr.reminder'],
    'hr.onboarding.invite': ROLE_PERMISSION_STATEMENTS['hr.onboarding.invite'],
    'hr.onboarding.task': ROLE_PERMISSION_STATEMENTS['hr.onboarding.task'],
    'hr.onboarding.checklist': ROLE_PERMISSION_STATEMENTS['hr.onboarding.checklist'],
    'hr.checklist.template': ROLE_PERMISSION_STATEMENTS['hr.checklist.template'],
    'hr.offboarding': ROLE_PERMISSION_STATEMENTS['hr.offboarding'],
    'hr.people.profile': ROLE_PERMISSION_STATEMENTS['hr.people.profile'],
    'hr.people.contract': ROLE_PERMISSION_STATEMENTS['hr.people.contract'],
    'hr.performance.review': ROLE_PERMISSION_STATEMENTS['hr.performance.review'],
    'hr.performance.goal': ROLE_PERMISSION_STATEMENTS['hr.performance.goal'],
    'hr.performance.feedback': ROLE_PERMISSION_STATEMENTS['hr.performance.feedback'],
    'hr.policy': ROLE_PERMISSION_STATEMENTS['hr.policy'],
    'hr.policy.acknowledgment': ROLE_PERMISSION_STATEMENTS['hr.policy.acknowledgment'],
    'hr.onboarding.feedback': ROLE_PERMISSION_STATEMENTS['hr.onboarding.feedback'],
    'hr.onboarding.email-sequence.template': ROLE_PERMISSION_STATEMENTS['hr.onboarding.email-sequence.template'],
    'hr.onboarding.workflow.template': ROLE_PERMISSION_STATEMENTS['hr.onboarding.workflow.template'],
    'hr.onboarding.metric.definition': ROLE_PERMISSION_STATEMENTS['hr.onboarding.metric.definition'],
    'hr.settings': ROLE_PERMISSION_STATEMENTS['hr.settings'],
    'hr.time.entry': ROLE_PERMISSION_STATEMENTS['hr.time.entry'],
    'hr.time.sheet': ROLE_PERMISSION_STATEMENTS['hr.time.sheet'],
    'hr.training.record': ROLE_PERMISSION_STATEMENTS['hr.training.record'],
    'hr.training.enrollment': ROLE_PERMISSION_STATEMENTS['hr.training.enrollment'],
  } satisfies OrgPermissionMap,
  inherits: ['member'],
  isSystem: true,
  isDefault: true,
} as const;

export const hrAdminTemplate = {
  name: 'hrAdmin',
  description: 'HR administrator with full HR module access.',
  scope: RoleScope.ORG,
  permissions: {
    'org.settings': ['read'],
    member: ['read', 'invite'],
    invitation: ROLE_PERMISSION_STATEMENTS.invitation,
    'hr.absence': ROLE_PERMISSION_STATEMENTS['hr.absence'],
    'hr.absence.settings': ROLE_PERMISSION_STATEMENTS['hr.absence.settings'],
    'hr.absence.attachment': ROLE_PERMISSION_STATEMENTS['hr.absence.attachment'],
    'hr.compliance.item': ROLE_PERMISSION_STATEMENTS['hr.compliance.item'],
    'hr.compliance.template': ROLE_PERMISSION_STATEMENTS['hr.compliance.template'],
    'hr.compliance.review': ROLE_PERMISSION_STATEMENTS['hr.compliance.review'],
    'hr.leave.request': ROLE_PERMISSION_STATEMENTS['hr.leave.request'],
    'hr.leave.balance': ROLE_PERMISSION_STATEMENTS['hr.leave.balance'],
    'hr.leave.policy': ROLE_PERMISSION_STATEMENTS['hr.leave.policy'],
    'hr.leave.type': ROLE_PERMISSION_STATEMENTS['hr.leave.type'],
    'hr.notification': ROLE_PERMISSION_STATEMENTS['hr.notification'],
    'hr.reminder': ROLE_PERMISSION_STATEMENTS['hr.reminder'],
    'hr.onboarding.invite': ROLE_PERMISSION_STATEMENTS['hr.onboarding.invite'],
    'hr.onboarding.task': ROLE_PERMISSION_STATEMENTS['hr.onboarding.task'],
    'hr.onboarding.checklist': ROLE_PERMISSION_STATEMENTS['hr.onboarding.checklist'],
    'hr.checklist.template': ROLE_PERMISSION_STATEMENTS['hr.checklist.template'],
    'hr.offboarding': ROLE_PERMISSION_STATEMENTS['hr.offboarding'],
    'hr.people.profile': ROLE_PERMISSION_STATEMENTS['hr.people.profile'],
    'hr.people.contract': ROLE_PERMISSION_STATEMENTS['hr.people.contract'],
    'hr.performance.review': ROLE_PERMISSION_STATEMENTS['hr.performance.review'],
    'hr.performance.goal': ROLE_PERMISSION_STATEMENTS['hr.performance.goal'],
    'hr.performance.feedback': ROLE_PERMISSION_STATEMENTS['hr.performance.feedback'],
    'hr.policy': ROLE_PERMISSION_STATEMENTS['hr.policy'],
    'hr.policy.acknowledgment': ROLE_PERMISSION_STATEMENTS['hr.policy.acknowledgment'],
    'hr.onboarding.feedback': ROLE_PERMISSION_STATEMENTS['hr.onboarding.feedback'],
    'hr.onboarding.email-sequence.template': ROLE_PERMISSION_STATEMENTS['hr.onboarding.email-sequence.template'],
    'hr.onboarding.workflow.template': ROLE_PERMISSION_STATEMENTS['hr.onboarding.workflow.template'],
    'hr.onboarding.metric.definition': ROLE_PERMISSION_STATEMENTS['hr.onboarding.metric.definition'],
    'hr.settings': ROLE_PERMISSION_STATEMENTS['hr.settings'],
    'hr.time.entry': ROLE_PERMISSION_STATEMENTS['hr.time.entry'],
    'hr.time.sheet': ROLE_PERMISSION_STATEMENTS['hr.time.sheet'],
    'hr.training.record': ROLE_PERMISSION_STATEMENTS['hr.training.record'],
    'hr.training.enrollment': ROLE_PERMISSION_STATEMENTS['hr.training.enrollment'],
  } satisfies OrgPermissionMap,
  inherits: ['member'],
  isSystem: true,
  isDefault: true,
} as const;
